export const culturaOptions = [
  { nome: "Soja (grão)", codigo: "001" },
  { nome: "Milho (grão)", codigo: "002" },
  { nome: "Algodão", codigo: "003" },
  { nome: "Amendoim", codigo: "004" },
  { nome: "Amendoim forrageiro (pastagem)", codigo: "005" },
  { nome: "Amendoim forrageiro (cobertura solo)", codigo: "006" },
  { nome: "Andropogon (pastagem)", codigo: "007" },
  { nome: "Andropogon (cobertura do solo)", codigo: "008" },
  { nome: "Azevém (pastagem)", codigo: "009" },
  { nome: "Azevém (cobertura do solo)", codigo: "010" },
  { nome: "Arroz terras altas (grão)", codigo: "011" },
  { nome: "Arroz terras baixas (inundado) (grão)", codigo: "012" },
  { nome: "Aveia branca (grão)", codigo: "013" },
  { nome: "Aveia branca (silagem/feno)", codigo: "014" },
  { nome: "Aveia branca (pastagem)", codigo: "015" },
  { nome: "Aveia branca (cobertura do solo)", codigo: "016" },
  { nome: "Aveia preta (grão)", codigo: "017" },
  { nome: "Aveia preta (silagem/feno)", codigo: "018" },
  { nome: "Aveia preta (pastagem)", codigo: "019" },
  { nome: "Aveia preta (cobertura do solo)", codigo: "020" },
  { nome: "Aveia amarela (grão)", codigo: "021" },
  { nome: "Aveia amarela (silagem/feno)", codigo: "022" },
  { nome: "Aveia amarela (pastagem)", codigo: "023" },
  { nome: "Aveia amarela (cobertura do solo)", codigo: "024" },
  { nome: "Brachiaria brizantha (pastagem)", codigo: "025" },
  { nome: "Brachiaria brizantha (cobertura do solo)", codigo: "026" },
  { nome: "Brachiaria decumbens (pastagem)", codigo: "027" },
  { nome: "Brachiaria decumbens (cobertura do solo)", codigo: "028" },
  { nome: "Brachiaria humidicola (pastagem)", codigo: "029" },
  { nome: "Brachiaria humidicola (cobertura do solo)", codigo: "030" },
  { nome: "Brachiaria ruziziensis (pastagem)", codigo: "031" },
  { nome: "Brachiaria ruziziensis (cobertura do solo)", codigo: "032" },
  { nome: "Canola (grão)", codigo: "033" },
  { nome: "Capim sudão (pastagem)", codigo: "034" },
  { nome: "Capim sudão (cobertura do solo)", codigo: "035" },
  { nome: "Capim Elefante (pastagem)", codigo: "036" },
  { nome: "Capim Elefante (cobertura do solo)", codigo: "037" },
  { nome: "Centeio (grão)", codigo: "038" },
  { nome: "Centeio (silagem/feno)", codigo: "039" },
  { nome: "Centeio (pastagem)", codigo: "040" },
  { nome: "Centeio (cobertura do solo)", codigo: "041" },
  { nome: "Cevada (grão)", codigo: "042" },
  { nome: "Cevada (silagem/feno)", codigo: "043" },
  { nome: "Cevada (pastagem)", codigo: "044" },
  { nome: "Cevada (cobertura do solo)", codigo: "045" },
  { nome: "Cornichão (silagem/feno)", codigo: "046" },
  { nome: "Cornichão (pastagem)", codigo: "047" },
  { nome: "Cornichão (cobertura do solo)", codigo: "048" },
  { nome: "Ervilha", codigo: "049" },
  { nome: "Ervilhaca (silagem/feno)", codigo: "050" },
  { nome: "Ervilhaca (pastagem)", codigo: "051" },
  { nome: "Ervilhaca (cobertura do solo)", codigo: "052" },
  { nome: "Estilosantes (silagem/feno)", codigo: "053" },
  { nome: "Estilosantes (pastagem)", codigo: "054" },
  { nome: "Estilosantes (cobertura do solo)", codigo: "055" },
  { nome: "Feijão (grão)", codigo: "056" },
  { nome: "Feijão caupi (grão)", codigo: "057" },
  { nome: "Feijão guandu (silagem/feno)", codigo: "058" },
  { nome: "Feijão guandu (pastagem)", codigo: "059" },
  { nome: "Feijão guandu (cobertura do solo)", codigo: "060" },
  { nome: "Gergelim (grão)", codigo: "061" },
  { nome: "Girassol (grão)", codigo: "062" },
  { nome: "Girassol (silagem/feno)", codigo: "063" },
  { nome: "Girassol (cobertura do solo)", codigo: "064" },
  { nome: "Grão de Bico (grão)", codigo: "065" },
  { nome: "Mamona (grão)", codigo: "066" },
  { nome: "Mandioca", codigo: "067" },
  { nome: "Milheto (grão)", codigo: "068" },
  { nome: "Milheto (silagem/feno)", codigo: "069" },
  { nome: "Milheto (pastagem)", codigo: "070" },
  { nome: "Milheto (cobertura do solo)", codigo: "071" },
  { nome: "Milho (silagem/feno)", codigo: "072" },
  { nome: "Mucuna(s) (cobertura do solo)", codigo: "073" },
  { nome: "Panicum maximum (silagem/feno)", codigo: "074" },
  { nome: "Panicum maximum (pastagem)", codigo: "075" },
  { nome: "Panicum maximum (cobertura do solo)", codigo: "076" },
  { nome: "Sorgo (grão)", codigo: "077" },
  { nome: "Sorgo (silagem/feno)", codigo: "078" },
  { nome: "Sorgo (pastagem)", codigo: "079" },
  { nome: "Sorgo (cobertura do solo)", codigo: "080" },
  { nome: "Tremoço branco (cobertura do solo)", codigo: "081" },
  { nome: "Trevo (silagem/feno)", codigo: "082" },
  { nome: "Trevo (pastagem)", codigo: "083" },
  { nome: "Trevo (cobertura do solo)", codigo: "084" },
  { nome: "Trigo (grão)", codigo: "085" },
  { nome: "Trigo (silagem/feno)", codigo: "086" },
  { nome: "Trigo (pastagem)", codigo: "087" },
  { nome: "Trigo (cobertura do solo)", codigo: "088" },
  { nome: "Triticale (grão)", codigo: "089" },
  { nome: "Triticale (silagem/feno)", codigo: "090" },
  { nome: "Triticale (pastagem)", codigo: "091" },
  { nome: "Triticale (cobertura do solo)", codigo: "092" },
  { nome: "Crotalária(s) (silagem/feno)", codigo: "093" },
  { nome: "Crotalária(s) (pastagem)", codigo: "094" },
  { nome: "Crotalária(s) (cobertura do solo)", codigo: "095" },
  { nome: "Nabo (cobertura do solo)", codigo: "096" },
  { nome: "Pousio, sem cultivo", codigo: "097" },
  { nome: "Mix 2 espécies (pelo menos 1 gramínia)", codigo: "098" },
  { nome: "Mix 2 espécies (sem gramínea)", codigo: "099" },
  { nome: "Mix 3 espécies (pelo menos 1 gramínia)", codigo: "100" },
  { nome: "Mix 3 espécies (sem gramínea)", codigo: "101" },
  { nome: "Mix 4 espécies (pelo menos 1 gramínia)", codigo: "102" },
  { nome: "Mix 4 espécies (sem gramínia)", codigo: "103" },
];
